Repository alma/alma-woocommerce-gateway, pull requests merged in 2024-11, with the labels that each got.

#289 fix: in page unmount
  src/assets/js/alma-checkout-in-page.js
Labels: type: bugfix

#290 Add getter for product variable config
  src/includes/AlmaSettings.php
  src/includes/Handlers/ProductHandler.php
Labels: type: feature

#294 security(aqua): use scanner image from private repository
  .github/workflows/aqua.yml
Labels: type: devx

#295 Update widget version to 3.4.0
  src/assets/widget/css/widgets.css
  src/assets/widget/js/widgets-wc.umd.js
  src/assets/widget/js/widgets-wc.umd.js.map
Labels: type: feature

#298 Feature/ecom 2261 translations loaded to early in woocommerce plugin
  src/alma-gateway-for-woocommerce.php
  src/includes/AlmaPlugin.php
Labels: bug
