Repository alma/alma-woocommerce-gateway, pull requests merged in 2024-10, with the labels that each got.

#281 Add hmac verification on ipn
  src/composer.json
  src/includes/Builders/Helpers/SecurityHelperBuilder.php
  src/includes/Exceptions/AlmaInvalidSignatureException.php
  src/includes/Helpers/PaymentHelper.php
  src/includes/Helpers/SecurityHelper.php
  src/includes/Traits/BuilderTrait.php
  src/tests/Builders/Helpers/SecurityHelperBuilderTest.php
  src/tests/Helpers/PaymentHelperTest.php
  src/tests/Helpers/SecurityHelperTest.php
Labels: type: feature

#282 Integrate credit on in page
  src/assets/js/alma-checkout-in-page.js
  src/includes/Admin/Helpers/FormFieldsHelper.php
  src/includes/AlmaPlugin.php
  src/includes/AlmaSettings.php
  src/includes/Gateways/Inpage/PayMoreThanFourGateway.php
  src/includes/Helpers/ConstantsHelper.php
  src/includes/Helpers/PlanHelper.php
  src/includes/Helpers/SettingsHelper.php
  src/includes/Services/CheckoutService.php
  src/tests/Helpers/SettingsHelperTest.php
Labels: type: feature

#285 Reuse Aqua workflow from alma/actions
  .github/workflows/aqua.yml
Labels: type: security

#286 Reintroduce full Aqua workflow due to repository privacy issues
  .github/workflows/aqua.yml
Labels: type: security

#287 fix: avoid blocking in-page if a notice is returned
  bin/build.sh
  src/includes/Services/CheckoutService.php
Labels: type: bugfix
