Repository alma/alma-woocommerce-gateway, pull requests merged in 2025-02, with the labels that each got.

#316 Collect auto_update plugins for gather cms data
  includes/Services/CollectCmsDataService.php
  tests/Services/CollectCmsDataServiceTest.php
Labels: type: feature

#319 Ci/fix linter
  .github/workflows/ci.yml
  composer.json
  sonar-project.properties
Labels: type: ci

#322 Use cdn for alma widget and update to version 4.x.x
  assets/widget/css/widgets.css
  assets/widget/js/widgets-wc.umd.js
  assets/widget/js/widgets-wc.umd.js.map
  bin/retrieve-widget-files.sh
  build/alma-checkout-block/alma-checkout-blocks.asset.php
  build/alma-checkout-block/alma-checkout-blocks.js
  build/alma-checkout-block/style-alma-checkout-blocks-rtl.css
  build/alma-checkout-block/style-alma-checkout-blocks.css
  includes/Blocks/AlmaWidgetBlock.php
  includes/Handlers/GenericHandler.php
  includes/Helpers/ConstantsHelper.php
Labels: type: feature

#326 Add payment method position to the gather cms data and fix typeError for display in page
  includes/AlmaSettings.php
  includes/Services/CollectCmsDataService.php
  includes/WcProxy/PaymentGatewaysProxy.php
  tests/Services/CollectCmsDataServiceTest.php
Labels: type: feature

#325 Fix/pre commit
  .editorconfig
  .pre-commit-config.yaml
  Taskfile.yml
  alma-gateway-for-woocommerce.php
  bin/coding-standard-fixer.sh
  bin/coding-standard.sh
  bin/lint-fix.sh
  bin/lint.sh
  bin/php-compatibility.sh
  compose.yml
  dockerfile.md
  includes/AlmaSettings.php
  includes/Blocks/AlmaBlock.php
  includes/Blocks/AlmaWidgetBlock.php
  includes/Handlers/GenericHandler.php
  legacy.Dockerfile
  lint.Dockerfile
  phpcs.xml
  sonar-project.properties
Labels: type: bugfix
