Repository alma/alma-woocommerce-gateway, pull requests merged in 2025-04, with the labels that each got.

#339 Feature/update ci
  .github/workflows/ci.yml
  .github/workflows/e2e-test.yaml
  README.md
  Taskfile.yml
  alma-gateway-for-woocommerce.php
  composer.json
Labels: type: feature

#343 fix: global style css in dashboard
  build/alma-checkout-block/alma-checkout-blocks-rtl.css
  build/alma-checkout-block/alma-checkout-blocks.asset.php
  build/alma-checkout-block/alma-checkout-blocks.css
  build/alma-checkout-block/alma-checkout-blocks.js
  build/alma-checkout-block/style-alma-checkout-blocks-rtl.css
  build/alma-checkout-block/style-alma-checkout-blocks.css
  build/alma-widget-block/alma-widget-block-rtl.css
  build/alma-widget-block/alma-widget-block-view-rtl.css
  build/alma-widget-block/alma-widget-block-view.asset.php
  build/alma-widget-block/alma-widget-block-view.css
  build/alma-widget-block/alma-widget-block-view.js
  build/alma-widget-block/alma-widget-block.asset.php
  build/alma-widget-block/alma-widget-block.css
  build/alma-widget-block/alma-widget-block.js
  src/alma-checkout-block/components/alma-blocks-component.tsx
Labels: type: bugfix

#345 Feature/ecom 2590 wc implement order confirmed event
  alma-gateway-for-woocommerce.php
  bin/install-wp-tests.sh
  includes/AlmaLogger.php
  includes/AlmaPlugin.php
  includes/Builders/Helpers/CartHelperBuilder.php
  includes/Exceptions/AlmaBusinessEventException.php
  includes/Helpers/CartHelper.php
  includes/Helpers/MigrationHelper.php
  includes/Helpers/ToolsHelper.php
  includes/Repositories/AlmaBusinessEventRepository.php
  includes/Services/AlmaBusinessEventService.php
  includes/Traits/BuilderTrait.php
  phpcs.xml
  tests/Helpers/CartHelperTest.php
  tests/Helpers/ToolsHelperTest.php
Labels: type: feature

#349 Fix/ecom 2682 velobrival in page in woocommerce
  includes/Helpers/PluginHelper.php
  includes/Traits/InPageGatewayTrait.php
Labels: bug

#350 fix: order confirmed business event with ipn + manual status changed
  includes/Helpers/OrderHelper.php
  includes/Repositories/AlmaBusinessEventRepository.php
  includes/Services/AlmaBusinessEventService.php
Labels: type: bugfix

#354 fix: in-page loading in certain event loading cases
  includes/Helpers/PluginHelper.php
  includes/Traits/InPageGatewayTrait.php
Labels: type: feature

#361 fix: in-page loading in certain event loading cases
  includes/Helpers/PluginHelper.php
  includes/Traits/InPageGatewayTrait.php
Labels: type: bugfix
